"""Adapted created_at and completed_at to Task

Revision ID: 020f9b4dbff2
Revises: 8448ccdf5698
Create Date: 2025-07-02 08:03:28.792714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020f9b4dbff2'
down_revision = '8448ccdf5698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
