"""Added debug column to force migrations

Revision ID: 0c14b2722228
Revises: 
Create Date: 2025-07-15 13:20:41.542695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c14b2722228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debug_column', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subject', schema=None) as batch_op:
        batch_op.drop_column('debug_column')

    # ### end Alembic commands ###
