"""New calendar columns for exam schema

Revision ID: 148a345c3330
Revises: 7bc7d7be24ae
Create Date: 2025-07-03 07:40:21.643870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148a345c3330'
down_revision = '7bc7d7be24ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at_exam', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at_exam', sa.DateTime(), nullable=True))
        batch_op.alter_column(
            'date',
            existing_type=sa.VARCHAR(length=50),
            type_=sa.DateTime(),
            existing_nullable=True,
            postgresql_using="date::timestamp without time zone"
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('completed_at_exam')
        batch_op.drop_column('created_at_exam')

    # ### end Alembic commands ###
