"""Added subject adaption to task model

Revision ID: 836a8626d93a
Revises: bbee2a046ea5
Create Date: 2025-07-18 16:03:10.863100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836a8626d93a'
down_revision = 'bbee2a046ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_task_subject_id',  # ← Add a meaningful name here
            'subject',
            ['subject_id'],
            ['id']
        )
        batch_op.drop_column('subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
