"""added new schema to avoid db errors

Revision ID: af45bc17e860
Revises: 0c14b2722228
Create Date: 2025-07-17 01:06:24.449078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af45bc17e860'
down_revision = '0c14b2722228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subject', schema=None) as batch_op:
        batch_op.drop_column('debug_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debug_column', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
