"""removed subject column in subject

Revision ID: bbee2a046ea5
Revises: af45bc17e860
Create Date: 2025-07-18 15:37:50.276403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbee2a046ea5'
down_revision = 'af45bc17e860'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('Subject')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subject_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), nullable=True),
    sa.Column('room', sa.VARCHAR(length=50), nullable=True),
    sa.Column('grade', sa.VARCHAR(length=100), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('subject_user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subject_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('subject')
    # ### end Alembic commands ###
